FROM python:3.12-alpine3.20

WORKDIR /workspace

RUN apk add --no-cache bash docker-cli docker-cli-compose git jq nodejs npm

COPY requirements.txt requirements-dev.txt ./
COPY docs/requirements.txt ./docs/requirements.txt
RUN python -m pip install --upgrade pip && \
    python -m pip install --no-cache-dir -r requirements-dev.txt

ENV PYTHONPATH=/workspace/src
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
