# Enforce TLS and client certificates for all remote connections.
local   all             all                                     trust
hostssl all             all             0.0.0.0/0               scram-sha-256 clientcert=verify-ca
hostssl all             all             ::/0                    scram-sha-256 clientcert=verify-ca
