"""REST API server for the skills service.

This server runs in its own Docker container and provides:
- /health - Health check endpoint
- /handle - Handle skill requests
- /heartbeat - Trigger heartbeat cycle
- /skills - List available skills
- /status - Get service status
"""

import asyncio
import base64
import hashlib
import hmac
import json
import math
import os
from collections.abc import Awaitable, Callable
from datetime import UTC, datetime, timedelta
from json import JSONDecodeError
from pathlib import Path
from typing import Any

from aiohttp import web

from zetherion_ai.admin.tenant_admin_manager import (
    AdminActorContext,
    TenantAdminManager,
    admin_actor_from_payload,
)
from zetherion_ai.logging import get_logger
from zetherion_ai.routing.models import DestinationType
from zetherion_ai.security.trust_policy import TrustPolicyEvaluator
from zetherion_ai.skills.base import SkillRequest
from zetherion_ai.skills.registry import SkillRegistry

log = get_logger("zetherion_ai.skills.server")

OAuthCallbackHandler = Callable[[web.Request], Awaitable[dict[str, Any]]]
OAuthAuthorizeHandler = Callable[[web.Request], Awaitable[dict[str, Any]]]


def _serialise_record(record: dict[str, Any]) -> dict[str, Any]:
    """Convert a DB record dict so it is JSON-serialisable (datetime → str)."""
    out: dict[str, Any] = {}
    for k, v in record.items():
        if hasattr(v, "isoformat"):
            out[k] = v.isoformat()
        else:
            out[k] = v
    return out


def _extract_json_object(raw: str) -> dict[str, Any]:
    """Best-effort JSON object extraction from model output."""
    text = raw.strip()
    if not text:
        return {}
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
        return {}
    except Exception:
        start = text.find("{")
        end = text.rfind("}")
        if start == -1 or end == -1 or end <= start:
            return {}
        try:
            parsed = json.loads(text[start : end + 1])
            return parsed if isinstance(parsed, dict) else {}
        except Exception:
            return {}


def _resolve_updater_secret() -> str:
    """Resolve updater secret from env or shared secret file.

    Skills and updater sidecar share ``/app/data``. If ``UPDATER_SECRET`` is
    not set, we read the secret generated by the sidecar.
    """
    explicit = os.environ.get("UPDATER_SECRET", "").strip()
    if explicit:
        return explicit

    secret_path = os.environ.get("UPDATER_SECRET_PATH", "/app/data/.updater-secret")
    path = Path(secret_path)
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8").strip()
    except Exception:
        log.warning("updater_secret_file_read_failed", path=secret_path)
        return ""


def _resolve_google_oauth(
    *,
    settings: Any,
) -> Any:
    """Resolve Google OAuth credentials dynamically from settings+secrets."""
    from zetherion_ai.config import get_dynamic, get_secret
    from zetherion_ai.skills.gmail.auth import GmailAuth

    env_client_id = settings.google_client_id or ""
    env_redirect_uri = settings.google_redirect_uri
    env_secret = (
        settings.google_client_secret.get_secret_value()
        if settings.google_client_secret is not None
        else None
    )

    client_id = str(get_dynamic("integrations", "google_client_id", env_client_id) or "").strip()
    redirect_uri = str(
        get_dynamic("integrations", "google_redirect_uri", env_redirect_uri) or env_redirect_uri
    ).strip()
    client_secret = str(get_secret("google_client_secret", env_secret) or "").strip()

    if not client_id:
        raise ValueError("Google OAuth client id is not configured")
    if not client_secret:
        raise ValueError("Google OAuth client secret is not configured")
    if not redirect_uri:
        raise ValueError("Google OAuth redirect URI is not configured")

    return GmailAuth(
        client_id=client_id,
        client_secret=client_secret,
        redirect_uri=redirect_uri,
    )


def _build_google_oauth_authorize_handler(
    *,
    auth_resolver: Callable[[], Any],
) -> OAuthAuthorizeHandler:
    """Build OAuth authorize handler that returns a provider auth URL."""

    async def _handler(request: web.Request) -> dict[str, Any]:
        raw_user_id = request.query.get("user_id", "").strip()
        if not raw_user_id:
            raise ValueError("Missing user_id query parameter")

        try:
            user_id = int(raw_user_id)
        except ValueError as exc:
            raise ValueError("Invalid user_id query parameter") from exc

        auth = auth_resolver()
        auth_url, state = auth.generate_auth_url(user_id)
        return {
            "ok": True,
            "provider": "google",
            "user_id": user_id,
            "auth_url": auth_url,
            "state": state,
        }

    return _handler


def _build_google_oauth_handler(
    *,
    auth_resolver: Callable[[], Any],
    account_manager: Any,
    integration_storage: Any,
) -> OAuthCallbackHandler:
    """Build OAuth callback handler for Google account linking."""

    async def _handler(request: web.Request) -> dict[str, Any]:
        auth = auth_resolver()
        oauth_error = request.query.get("error")
        if oauth_error:
            raise ValueError(f"Google OAuth failed: {oauth_error}")

        code = request.query.get("code", "").strip()
        state = request.query.get("state", "").strip()
        if not code or not state:
            raise ValueError("Missing OAuth code/state")

        user_id = auth.validate_state_token(state)
        token_data = await auth.exchange_code(code)
        access_token = str(token_data.get("access_token") or "")
        refresh_token = str(token_data.get("refresh_token") or "")
        if not access_token:
            raise ValueError("Google OAuth did not return access_token")

        email_addr = await auth.get_user_email(access_token)
        if not email_addr:
            raise ValueError("Google OAuth did not provide account email")

        if not refresh_token:
            existing = await account_manager.get_account_by_email(user_id, email_addr)
            if existing is not None:
                refresh_token = existing.refresh_token
        if not refresh_token:
            raise ValueError("Google OAuth did not return refresh_token")

        expires_in = int(token_data.get("expires_in") or 3600)
        token_expiry = datetime.now(UTC) + timedelta(seconds=expires_in)
        raw_scopes = token_data.get("scope") or ""
        scopes = [s for s in str(raw_scopes).split() if s]

        account_id = await account_manager.add_account(
            user_id=user_id,
            email_addr=email_addr,
            access_token=access_token,
            refresh_token=refresh_token,
            token_expiry=token_expiry,
            scopes=scopes,
        )

        await integration_storage.upsert_account(
            user_id=user_id,
            provider="google",
            account_ref=str(account_id),
            email=email_addr,
            scopes=scopes,
            is_primary=False,
            metadata={"account_email": email_addr},
        )
        await integration_storage.upsert_destination(
            user_id=user_id,
            provider="google",
            account_ref=str(account_id),
            destination_id=email_addr,
            destination_type=DestinationType.MAILBOX,
            display_name=email_addr,
            is_primary=False,
            writable=True,
            metadata={"account_id": account_id},
        )

        return {
            "ok": True,
            "provider": "google",
            "user_id": user_id,
            "account_email": email_addr,
            "account_id": account_id,
        }

    return _handler


class SkillsServer:
    """REST API server for skills service.

    Provides endpoints for the bot to interact with skills,
    plus user management and runtime settings CRUD.
    """

    def __init__(
        self,
        registry: SkillRegistry,
        api_secret: str | None = None,
        admin_actor_secret: str | None = None,
        host: str = "0.0.0.0",  # nosec B104 - Intentional for Docker container
        port: int = 8080,
        user_manager: Any | None = None,
        settings_manager: Any | None = None,
        secrets_manager: Any | None = None,
        tenant_admin_manager: TenantAdminManager | None = None,
        oauth_handlers: dict[str, OAuthCallbackHandler] | None = None,
        oauth_authorizers: dict[str, OAuthAuthorizeHandler] | None = None,
    ):
        """Initialize the skills server.

        Args:
            registry: The skill registry.
            api_secret: Optional shared secret for authentication.
            host: Host to bind to.
            port: Port to listen on.
            user_manager: Optional UserManager for RBAC API.
            settings_manager: Optional SettingsManager for settings API.
        """
        self._registry = registry
        self._api_secret = api_secret
        self._admin_actor_secret = (admin_actor_secret or api_secret or "").strip()
        self._host = host
        self._port = port
        self._user_manager = user_manager
        self._settings_manager = settings_manager
        self._secrets_manager = secrets_manager
        self._tenant_admin_manager = tenant_admin_manager
        self._oauth_handlers = oauth_handlers or {}
        self._oauth_authorizers = oauth_authorizers or {}
        self._admin_nonce_cache: dict[str, datetime] = {}
        self._admin_nonce_ttl = timedelta(minutes=10)
        self._admin_actor_max_skew = timedelta(minutes=5)
        self._bridge_nonce_cache: dict[str, datetime] = {}
        self._bridge_nonce_ttl = timedelta(minutes=10)
        self._bridge_max_skew = timedelta(minutes=5)
        self._bridge_signing_secret = os.environ.get("WHATSAPP_BRIDGE_SIGNING_SECRET", "").strip()
        self._trust_policy_evaluator = TrustPolicyEvaluator()
        self._app: web.Application | None = None
        self._runner: web.AppRunner | None = None

        log.info("skills_server_initialized", host=host, port=port)

    def _check_auth(self, request: web.Request) -> bool:
        """Check if request is authenticated.

        Args:
            request: The incoming request.

        Returns:
            True if authenticated or no secret required.
        """
        if not self._api_secret:
            return True

        provided = request.headers.get("X-API-Secret")
        return provided is not None and hmac.compare_digest(provided, self._api_secret)

    @staticmethod
    async def _read_json_object(request: web.Request) -> dict[str, Any]:
        """Read request JSON and ensure the payload is a JSON object."""
        try:
            data = await request.json()
        except (ValueError, JSONDecodeError) as err:
            raise ValueError("Invalid JSON body") from err
        if not isinstance(data, dict):
            raise ValueError("JSON body must be an object")
        return data

    @staticmethod
    def _parse_int(raw: Any, field_name: str) -> int:
        """Parse an integer field and raise ValueError on invalid input."""
        try:
            return int(raw)
        except (TypeError, ValueError) as err:
            raise ValueError(f"Invalid integer for '{field_name}'") from err

    @staticmethod
    def _parse_bool(raw: Any, field_name: str, default: bool = True) -> bool:
        """Parse a boolean field and raise ValueError on invalid input."""
        if raw is None:
            return default
        if isinstance(raw, bool):
            return raw
        if isinstance(raw, int | float):
            return bool(raw)
        if isinstance(raw, str):
            normalized = raw.strip().lower()
            if normalized in {"1", "true", "yes", "on"}:
                return True
            if normalized in {"0", "false", "no", "off"}:
                return False
        raise ValueError(f"Invalid boolean for '{field_name}'")

    @staticmethod
    def _is_tenant_admin_path(path: str) -> bool:
        """Return True for tenant-admin endpoints requiring actor envelope."""
        return path.startswith("/admin/tenants/")

    def _prune_admin_nonce_cache(self, now: datetime) -> None:
        expired = [nonce for nonce, expiry in self._admin_nonce_cache.items() if expiry <= now]
        for nonce in expired:
            self._admin_nonce_cache.pop(nonce, None)

    def _prune_bridge_nonce_cache(self, now: datetime) -> None:
        expired = [nonce for nonce, expiry in self._bridge_nonce_cache.items() if expiry <= now]
        for nonce in expired:
            self._bridge_nonce_cache.pop(nonce, None)

    def _resolve_bridge_signing_secret(self, tenant_id: str) -> str:
        if self._tenant_admin_manager is not None:
            tenant_secret = self._tenant_admin_manager.get_secret_cached(
                tenant_id,
                "WHATSAPP_BRIDGE_SIGNING_SECRET",
                default="",
            )
            if tenant_secret:
                return tenant_secret
        return self._bridge_signing_secret

    def _verify_bridge_signature(
        self,
        *,
        request: web.Request,
        tenant_id: str,
        raw_body: str,
    ) -> None:
        timestamp = request.headers.get("X-Bridge-Timestamp", "").strip()
        nonce = request.headers.get("X-Bridge-Nonce", "").strip()
        provided_signature = request.headers.get("X-Bridge-Signature", "").strip().lower()
        if not timestamp or not nonce or not provided_signature:
            raise ValueError("Missing bridge signature headers")

        try:
            timestamp_int = int(timestamp)
        except ValueError as exc:
            raise ValueError("Invalid X-Bridge-Timestamp header") from exc

        now = datetime.now(UTC)
        signed_at = datetime.fromtimestamp(timestamp_int, tz=UTC)
        skew = now - signed_at
        if skew > self._bridge_max_skew or skew < -self._bridge_max_skew:
            raise ValueError("Expired bridge signature timestamp")

        signing_secret = self._resolve_bridge_signing_secret(tenant_id)
        if not signing_secret:
            raise ValueError("Bridge signing secret is not configured")

        canonical = f"{tenant_id}.{timestamp}.{nonce}.{raw_body}"
        expected_signature = hmac.new(
            signing_secret.encode("utf-8"),
            canonical.encode("utf-8"),
            hashlib.sha256,
        ).hexdigest()
        if not hmac.compare_digest(provided_signature, expected_signature):
            raise ValueError("Invalid bridge signature")

        self._prune_bridge_nonce_cache(now)
        nonce_key = f"{tenant_id}:{nonce}"
        if nonce_key in self._bridge_nonce_cache:
            raise RuntimeError("Bridge nonce replay detected")
        self._bridge_nonce_cache[nonce_key] = now + self._bridge_nonce_ttl

    @staticmethod
    def _decode_actor_payload(encoded: str) -> dict[str, Any]:
        if not encoded.strip():
            raise ValueError("Missing admin actor envelope")
        padding = "=" * ((4 - len(encoded) % 4) % 4)
        try:
            decoded = base64.urlsafe_b64decode((encoded + padding).encode("ascii"))
            payload = json.loads(decoded.decode("utf-8"))
        except Exception as exc:
            raise ValueError("Invalid admin actor envelope") from exc
        if not isinstance(payload, dict):
            raise ValueError("Invalid admin actor envelope")
        return payload

    def _verify_admin_actor(self, request: web.Request) -> AdminActorContext:
        if not self._admin_actor_secret:
            raise ValueError("Admin actor secret is not configured")

        encoded_actor = request.headers.get("X-Admin-Actor", "").strip()
        provided_signature = request.headers.get("X-Admin-Signature", "").strip()
        if not encoded_actor or not provided_signature:
            raise ValueError("Missing admin actor signature headers")

        expected_signature = hmac.new(
            self._admin_actor_secret.encode("utf-8"),
            encoded_actor.encode("utf-8"),
            hashlib.sha256,
        ).hexdigest()
        if not hmac.compare_digest(provided_signature, expected_signature):
            raise ValueError("Invalid admin actor signature")

        payload = self._decode_actor_payload(encoded_actor)
        actor = admin_actor_from_payload(payload)

        now = datetime.now(UTC)
        skew = now - actor.timestamp
        if skew > self._admin_actor_max_skew or skew < -self._admin_actor_max_skew:
            raise ValueError("Expired admin actor envelope")

        self._prune_admin_nonce_cache(now)
        nonce_key = f"{actor.actor_sub}:{actor.nonce}"
        if nonce_key in self._admin_nonce_cache:
            raise ValueError("Replayed admin actor envelope")
        self._admin_nonce_cache[nonce_key] = now + self._admin_nonce_ttl
        return actor

    @web.middleware
    async def auth_middleware(
        self,
        request: web.Request,
        handler: Any,
    ) -> web.Response:
        """Middleware to check authentication.

        Args:
            request: The incoming request.
            handler: The route handler.

        Returns:
            Response from handler or 401 if unauthorized.
        """
        response: web.Response
        # Skip auth for health check
        if request.path == "/health":
            response = await handler(request)
            return response
        if request.path == "/gmail/callback" or (
            request.path.startswith("/oauth/") and request.path.endswith("/callback")
        ):
            response = await handler(request)
            return response

        if not self._check_auth(request):
            return web.json_response(
                {"error": "Unauthorized"},
                status=401,
            )

        if self._is_tenant_admin_path(request.path):
            try:
                request["admin_actor"] = self._verify_admin_actor(request)
            except ValueError as exc:
                return web.json_response({"error": str(exc)}, status=401)

        response = await handler(request)
        return response

    @staticmethod
    def _admin_actor(request: web.Request) -> AdminActorContext:
        actor = request.get("admin_actor")
        if not isinstance(actor, AdminActorContext):
            raise ValueError("Missing admin actor context")
        return actor

    async def handle_health(self, request: web.Request) -> web.Response:
        """Health check endpoint.

        Args:
            request: The incoming request.

        Returns:
            200 OK with status.
        """
        return web.json_response(
            {
                "status": "healthy",
                "skills_ready": len(self._registry.list_ready_skills()),
                "skills_total": self._registry.skill_count,
            }
        )

    async def handle_request(self, request: web.Request) -> web.Response:
        """Handle skill request endpoint.

        Args:
            request: The incoming request with skill request body.

        Returns:
            Response from the skill.
        """
        try:
            data = await self._read_json_object(request)
            skill_request = SkillRequest.from_dict(data)

            response = await self._registry.handle_request(skill_request)

            return web.json_response(response.to_dict())

        except ValueError as e:
            return web.json_response({"error": str(e)}, status=400)
        except Exception:
            log.exception("handle_request_error")
            return web.json_response(
                {"error": "Internal server error"},
                status=500,
            )

    async def handle_heartbeat(self, request: web.Request) -> web.Response:
        """Heartbeat endpoint.

        Args:
            request: The incoming request with user_ids.

        Returns:
            List of heartbeat actions.
        """
        try:
            data = await self._read_json_object(request)
            user_ids = data.get("user_ids", [])

            actions = await self._registry.run_heartbeat(user_ids)

            return web.json_response(
                {
                    "actions": [a.to_dict() for a in actions],
                }
            )

        except ValueError as e:
            return web.json_response({"error": str(e)}, status=400)
        except Exception:
            log.exception("heartbeat_error")
            return web.json_response(
                {"error": "Internal server error"},
                status=500,
            )

    async def handle_list_skills(self, request: web.Request) -> web.Response:
        """List skills endpoint.

        Args:
            request: The incoming request.

        Returns:
            List of skill metadata.
        """
        skills = self._registry.list_skills()
        return web.json_response(
            {
                "skills": [s.to_dict() for s in skills],
            }
        )

    async def handle_get_skill(self, request: web.Request) -> web.Response:
        """Get specific skill endpoint.

        Args:
            request: The incoming request.

        Returns:
            Skill metadata or 404.
        """
        name = request.match_info.get("name", "")
        skill = self._registry.get_skill(name)

        if skill is None:
            return web.json_response(
                {"error": "Skill not found"},
                status=404,
            )

        return web.json_response(skill.metadata.to_dict())

    async def handle_status(self, request: web.Request) -> web.Response:
        """Status endpoint.

        Args:
            request: The incoming request.

        Returns:
            Service status.
        """
        return web.json_response(self._registry.get_status_summary())

    async def handle_prompt_fragments(self, request: web.Request) -> web.Response:
        """Get prompt fragments endpoint.

        Args:
            request: The incoming request with user_id param.

        Returns:
            List of prompt fragments.
        """
        user_id = request.query.get("user_id", "")

        fragments = self._registry.get_system_prompt_fragments(user_id)

        return web.json_response(
            {
                "fragments": fragments,
            }
        )

    async def handle_intents(self, request: web.Request) -> web.Response:
        """List intents endpoint.

        Args:
            request: The incoming request.

        Returns:
            Mapping of intents to skills.
        """
        return web.json_response(
            {
                "intents": self._registry.list_intents(),
            }
        )

    async def handle_oauth_callback(self, request: web.Request) -> web.Response:
        """Handle provider OAuth callbacks without API-secret auth."""
        provider = request.match_info.get("provider", "").strip().lower()
        if not provider:
            return web.json_response({"error": "Missing provider"}, status=400)

        handler = self._oauth_handlers.get(provider)
        if handler is None:
            return web.json_response(
                {"error": f"OAuth callback provider '{provider}' is not configured"},
                status=404,
            )

        try:
            result = await handler(request)
            return web.json_response(result)
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)
        except Exception:
            log.exception("oauth_callback_failed", provider=provider)
            return web.json_response({"error": "OAuth callback failed"}, status=500)

    async def handle_oauth_authorize(self, request: web.Request) -> web.Response:
        """Generate provider OAuth authorization URL."""
        provider = request.match_info.get("provider", "").strip().lower()
        if not provider:
            return web.json_response({"error": "Missing provider"}, status=400)

        handler = self._oauth_authorizers.get(provider)
        if handler is None:
            return web.json_response(
                {"error": f"OAuth authorize provider '{provider}' is not configured"},
                status=404,
            )

        try:
            result = await handler(request)
            return web.json_response(result)
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)
        except Exception:
            log.exception("oauth_authorize_failed", provider=provider)
            return web.json_response({"error": "OAuth authorize failed"}, status=500)

    async def handle_gmail_callback_alias(self, request: web.Request) -> web.Response:
        """Backward-compatible Gmail callback route alias."""
        handler = self._oauth_handlers.get("google")
        if handler is None:
            return web.json_response(
                {"error": "OAuth callback provider 'google' is not configured"},
                status=404,
            )
        try:
            result = await handler(request)
            return web.json_response(result)
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)
        except Exception:
            log.exception("oauth_callback_failed", provider="google")
            return web.json_response({"error": "OAuth callback failed"}, status=500)

    # ------------------------------------------------------------------
    # User management API
    # ------------------------------------------------------------------

    async def handle_list_users(self, request: web.Request) -> web.Response:
        """GET /users — list users, optionally filtered by role."""
        if self._user_manager is None:
            return web.json_response({"error": "User management not configured"}, status=501)
        role = request.query.get("role")
        users = await self._user_manager.list_users(role_filter=role)
        return web.json_response({"users": [_serialise_record(u) for u in users]})

    async def handle_add_user(self, request: web.Request) -> web.Response:
        """POST /users — add a user."""
        if self._user_manager is None:
            return web.json_response({"error": "User management not configured"}, status=501)
        try:
            data = await self._read_json_object(request)
            user_id = self._parse_int(data.get("user_id"), "user_id")
            added_by = self._parse_int(data.get("added_by"), "added_by")
        except ValueError as e:
            return web.json_response({"error": str(e)}, status=400)
        success = await self._user_manager.add_user(
            user_id=user_id,
            role=data.get("role", "user"),
            added_by=added_by,
        )
        if success:
            return web.json_response({"ok": True}, status=201)
        return web.json_response(
            {"ok": False, "error": "Permission denied or invalid role"}, status=403
        )

    async def handle_delete_user(self, request: web.Request) -> web.Response:
        """DELETE /users/{user_id} — remove a user."""
        if self._user_manager is None:
            return web.json_response({"error": "User management not configured"}, status=501)
        try:
            user_id = self._parse_int(request.match_info.get("user_id"), "user_id")
            removed_by = self._parse_int(request.query.get("removed_by", "0"), "removed_by")
        except ValueError as e:
            return web.json_response({"error": str(e)}, status=400)
        success = await self._user_manager.remove_user(user_id=user_id, removed_by=removed_by)
        if success:
            return web.json_response({"ok": True})
        return web.json_response(
            {"ok": False, "error": "Permission denied or user not found"}, status=403
        )

    async def handle_patch_user_role(self, request: web.Request) -> web.Response:
        """PATCH /users/{user_id}/role — change a user's role."""
        if self._user_manager is None:
            return web.json_response({"error": "User management not configured"}, status=501)
        try:
            user_id = self._parse_int(request.match_info.get("user_id"), "user_id")
            data = await self._read_json_object(request)
            changed_by = self._parse_int(data.get("changed_by"), "changed_by")
        except ValueError as e:
            return web.json_response({"error": str(e)}, status=400)
        success = await self._user_manager.set_role(
            user_id=user_id,
            new_role=data["role"],
            changed_by=changed_by,
        )
        if success:
            return web.json_response({"ok": True})
        return web.json_response(
            {"ok": False, "error": "Permission denied or invalid role"}, status=403
        )

    async def handle_audit_log(self, request: web.Request) -> web.Response:
        """GET /users/audit — recent audit log entries."""
        if self._user_manager is None:
            return web.json_response({"error": "User management not configured"}, status=501)
        try:
            limit = self._parse_int(request.query.get("limit", "50"), "limit")
        except ValueError as e:
            return web.json_response({"error": str(e)}, status=400)
        entries = await self._user_manager.get_audit_log(limit=limit)
        return web.json_response({"entries": [_serialise_record(e) for e in entries]})

    # ------------------------------------------------------------------
    # Settings API
    # ------------------------------------------------------------------

    async def handle_list_settings(self, request: web.Request) -> web.Response:
        """GET /settings — list all settings."""
        if self._settings_manager is None:
            return web.json_response({"error": "Settings not configured"}, status=501)
        namespace = request.query.get("namespace")
        settings = await self._settings_manager.get_all(namespace=namespace)
        return web.json_response({"settings": settings})

    async def handle_get_setting(self, request: web.Request) -> web.Response:
        """GET /settings/{namespace}/{key} — get a specific setting."""
        if self._settings_manager is None:
            return web.json_response({"error": "Settings not configured"}, status=501)
        namespace = request.match_info["namespace"]
        key = request.match_info["key"]
        value = self._settings_manager.get(namespace, key)
        return web.json_response({"namespace": namespace, "key": key, "value": value})

    async def handle_put_setting(self, request: web.Request) -> web.Response:
        """PUT /settings/{namespace}/{key} — update a setting."""
        if self._settings_manager is None:
            return web.json_response({"error": "Settings not configured"}, status=501)
        namespace = request.match_info["namespace"]
        key = request.match_info["key"]
        try:
            data = await self._read_json_object(request)
            await self._settings_manager.set(
                namespace=namespace,
                key=key,
                value=data["value"],
                changed_by=self._parse_int(data.get("changed_by", 0), "changed_by"),
                data_type=data.get("data_type", "string"),
            )
            return web.json_response({"ok": True})
        except ValueError as e:
            return web.json_response({"error": str(e)}, status=400)

    async def handle_delete_setting(self, request: web.Request) -> web.Response:
        """DELETE /settings/{namespace}/{key} — remove a setting override."""
        if self._settings_manager is None:
            return web.json_response({"error": "Settings not configured"}, status=501)
        namespace = request.match_info["namespace"]
        key = request.match_info["key"]
        try:
            deleted_by = self._parse_int(request.query.get("deleted_by", "0"), "deleted_by")
        except ValueError as e:
            return web.json_response({"error": str(e)}, status=400)
        deleted = await self._settings_manager.delete(
            namespace=namespace, key=key, deleted_by=deleted_by
        )
        return web.json_response({"ok": True, "existed": deleted})

    async def handle_list_secrets(self, request: web.Request) -> web.Response:
        """GET /secrets — list secret metadata (never returns secret values)."""
        if self._secrets_manager is None:
            return web.json_response({"error": "Secrets not configured"}, status=501)
        records = await self._secrets_manager.get_metadata()
        return web.json_response({"secrets": [_serialise_record(r) for r in records]})

    async def handle_put_secret(self, request: web.Request) -> web.Response:
        """PUT /secrets/{name} — create/update an encrypted secret."""
        if self._secrets_manager is None:
            return web.json_response({"error": "Secrets not configured"}, status=501)
        name = request.match_info["name"]
        try:
            data = await self._read_json_object(request)
            value = str(data.get("value", ""))
            if not value:
                raise ValueError("Missing non-empty secret 'value'")
            await self._secrets_manager.set(
                name=name,
                value=value,
                changed_by=self._parse_int(data.get("changed_by", 0), "changed_by"),
                description=data.get("description"),
            )
            return web.json_response({"ok": True})
        except ValueError as e:
            return web.json_response({"error": str(e)}, status=400)

    async def handle_delete_secret(self, request: web.Request) -> web.Response:
        """DELETE /secrets/{name} — delete a stored secret."""
        if self._secrets_manager is None:
            return web.json_response({"error": "Secrets not configured"}, status=501)
        name = request.match_info["name"]
        try:
            deleted_by = self._parse_int(request.query.get("deleted_by", "0"), "deleted_by")
        except ValueError as e:
            return web.json_response({"error": str(e)}, status=400)
        deleted = await self._secrets_manager.delete(name=name, deleted_by=deleted_by)
        return web.json_response({"ok": True, "existed": deleted})

    # ------------------------------------------------------------------
    # Tenant admin API (internal-only)
    # ------------------------------------------------------------------

    async def handle_tenant_list_discord_users(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        users = await self._tenant_admin_manager.list_discord_users(tenant_id)
        return web.json_response({"users": [_serialise_record(row) for row in users]})

    async def handle_tenant_add_discord_user(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            actor = self._admin_actor(request)
            data = await self._read_json_object(request)
            discord_user_id = self._parse_int(data.get("discord_user_id"), "discord_user_id")
            role = str(data.get("role", "user")).strip() or "user"
            row = await self._tenant_admin_manager.upsert_discord_user(
                tenant_id=tenant_id,
                discord_user_id=discord_user_id,
                role=role,
                actor=actor,
            )
            return web.json_response({"ok": True, "user": _serialise_record(row)}, status=201)
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_delete_discord_user(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            actor = self._admin_actor(request)
            discord_user_id = self._parse_int(
                request.match_info.get("discord_user_id"), "discord_user_id"
            )
            deleted = await self._tenant_admin_manager.delete_discord_user(
                tenant_id=tenant_id,
                discord_user_id=discord_user_id,
                actor=actor,
            )
            return web.json_response({"ok": True, "existed": deleted})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_patch_discord_user_role(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            actor = self._admin_actor(request)
            discord_user_id = self._parse_int(
                request.match_info.get("discord_user_id"), "discord_user_id"
            )
            data = await self._read_json_object(request)
            role = str(data.get("role", "")).strip()
            if not role:
                raise ValueError("Missing role")
            changed = await self._tenant_admin_manager.update_discord_user_role(
                tenant_id=tenant_id,
                discord_user_id=discord_user_id,
                role=role,
                actor=actor,
            )
            return web.json_response({"ok": True, "changed": changed})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_list_discord_bindings(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        rows = await self._tenant_admin_manager.list_discord_bindings(tenant_id)
        return web.json_response({"bindings": [_serialise_record(row) for row in rows]})

    async def handle_tenant_put_guild_binding(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            actor = self._admin_actor(request)
            guild_id = self._parse_int(request.match_info.get("guild_id"), "guild_id")
            data = await self._read_json_object(request)
            priority = self._parse_int(data.get("priority", 100), "priority")
            is_active = self._parse_bool(data.get("is_active"), "is_active", default=True)
            row = await self._tenant_admin_manager.put_guild_binding(
                tenant_id=tenant_id,
                guild_id=guild_id,
                priority=priority,
                is_active=is_active,
                actor=actor,
            )
            return web.json_response({"ok": True, "binding": _serialise_record(row)})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_put_channel_binding(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            actor = self._admin_actor(request)
            channel_id = self._parse_int(request.match_info.get("channel_id"), "channel_id")
            data = await self._read_json_object(request)
            guild_id = self._parse_int(data.get("guild_id"), "guild_id")
            priority = self._parse_int(data.get("priority", 100), "priority")
            is_active = self._parse_bool(data.get("is_active"), "is_active", default=True)
            row = await self._tenant_admin_manager.put_channel_binding(
                tenant_id=tenant_id,
                guild_id=guild_id,
                channel_id=channel_id,
                priority=priority,
                is_active=is_active,
                actor=actor,
            )
            return web.json_response({"ok": True, "binding": _serialise_record(row)})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_delete_channel_binding(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            actor = self._admin_actor(request)
            channel_id = self._parse_int(request.match_info.get("channel_id"), "channel_id")
            deleted = await self._tenant_admin_manager.delete_channel_binding(
                tenant_id=tenant_id,
                channel_id=channel_id,
                actor=actor,
            )
            return web.json_response({"ok": True, "existed": deleted})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_list_settings(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        namespace = request.query.get("namespace")
        rows = await self._tenant_admin_manager.list_settings(tenant_id, namespace=namespace)
        return web.json_response({"settings": rows})

    async def handle_tenant_put_setting(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        namespace = request.match_info["namespace"]
        key = request.match_info["key"]
        try:
            actor = self._admin_actor(request)
            data = await self._read_json_object(request)
            if "value" not in data:
                raise ValueError("Missing setting value")
            await self._tenant_admin_manager.set_setting(
                tenant_id=tenant_id,
                namespace=namespace,
                key=key,
                value=data["value"],
                data_type=str(data.get("data_type", "string")),
                actor=actor,
            )
            return web.json_response({"ok": True})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_delete_setting(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        namespace = request.match_info["namespace"]
        key = request.match_info["key"]
        try:
            actor = self._admin_actor(request)
            deleted = await self._tenant_admin_manager.delete_setting(
                tenant_id=tenant_id,
                namespace=namespace,
                key=key,
                actor=actor,
            )
            return web.json_response({"ok": True, "existed": deleted})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_list_secrets(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        rows = await self._tenant_admin_manager.list_secret_metadata(tenant_id)
        return web.json_response({"secrets": [_serialise_record(row) for row in rows]})

    async def handle_tenant_put_secret(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        name = request.match_info["name"]
        try:
            actor = self._admin_actor(request)
            data = await self._read_json_object(request)
            value = str(data.get("value", ""))
            if not value:
                raise ValueError("Missing non-empty secret value")
            row = await self._tenant_admin_manager.set_secret(
                tenant_id=tenant_id,
                name=name,
                value=value,
                description=str(data["description"]) if "description" in data else None,
                actor=actor,
            )
            return web.json_response({"ok": True, "secret": _serialise_record(row)})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_delete_secret(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        name = request.match_info["name"]
        try:
            actor = self._admin_actor(request)
            deleted = await self._tenant_admin_manager.delete_secret(
                tenant_id=tenant_id,
                name=name,
                actor=actor,
            )
            return web.json_response({"ok": True, "existed": deleted})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_list_audit(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            limit = self._parse_int(request.query.get("limit", "200"), "limit")
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)
        rows = await self._tenant_admin_manager.list_audit(tenant_id, limit=limit)
        return web.json_response({"entries": [_serialise_record(row) for row in rows]})

    async def handle_tenant_get_email_provider_config(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        provider = request.match_info.get("provider", "google")
        try:
            config = await self._tenant_admin_manager.get_email_provider_config(
                tenant_id=tenant_id,
                provider=provider,
            )
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)
        if config is None:
            return web.json_response({"error": "Email provider config not found"}, status=404)
        return web.json_response({"provider_config": _serialise_record(config)})

    async def handle_tenant_put_email_provider_config(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        provider = request.match_info.get("provider", "google")
        try:
            actor = self._admin_actor(request)
            data = await self._read_json_object(request)
            redirect_uri = str(data.get("redirect_uri", "")).strip()
            if not redirect_uri:
                raise ValueError("Missing redirect_uri")
            enabled = self._parse_bool(data.get("enabled"), "enabled", default=True)
            config = await self._tenant_admin_manager.put_email_provider_config(
                tenant_id=tenant_id,
                provider=provider,
                client_id=str(data.get("client_id") or "").strip() or None,
                client_secret=str(data.get("client_secret") or "").strip() or None,
                redirect_uri=redirect_uri,
                enabled=enabled,
                actor=actor,
                metadata=data.get("metadata") if isinstance(data.get("metadata"), dict) else None,
                client_id_ref=str(data.get("client_id_ref") or "").strip() or None,
                client_secret_ref=str(data.get("client_secret_ref") or "").strip() or None,
            )
            return web.json_response({"ok": True, "provider_config": _serialise_record(config)})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_start_email_oauth(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            actor = self._admin_actor(request)
            data = await self._read_json_object(request)
            provider = str(data.get("provider") or "google")
            result = await self._tenant_admin_manager.create_email_oauth_start(
                tenant_id=tenant_id,
                provider=provider,
                actor=actor,
                account_hint=str(data.get("account_hint") or "").strip() or None,
            )
            return web.json_response({"ok": True, **result}, status=201)
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_exchange_email_oauth(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        provider = request.match_info.get("provider", "google").strip().lower()
        if provider != "google":
            return web.json_response({"error": f"Unsupported provider '{provider}'"}, status=400)
        try:
            actor = self._admin_actor(request)
            data = await self._read_json_object(request)
            code = str(data.get("code") or "").strip()
            state = str(data.get("state") or "").strip()
            if not code or not state:
                raise ValueError("Missing OAuth code/state")
            account = await self._tenant_admin_manager.exchange_google_oauth_code(
                tenant_id=tenant_id,
                code=code,
                state=state,
                actor=actor,
            )
            return web.json_response({"ok": True, "account": _serialise_record(account)})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_list_email_accounts(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        provider = request.query.get("provider", "google")
        try:
            rows = await self._tenant_admin_manager.list_email_accounts(
                tenant_id=tenant_id,
                provider=provider,
            )
            return web.json_response({"accounts": [_serialise_record(row) for row in rows]})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_patch_email_account(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        account_id = request.match_info["account_id"]
        try:
            actor = self._admin_actor(request)
            data = await self._read_json_object(request)
            metadata = data.get("metadata")
            if metadata is not None and not isinstance(metadata, dict):
                raise ValueError("metadata must be an object when provided")
            patched = await self._tenant_admin_manager.patch_email_account(
                tenant_id=tenant_id,
                account_id=account_id,
                actor=actor,
                status=str(data.get("status")).strip() if data.get("status") is not None else None,
                metadata=metadata,
                sync_cursor=(
                    str(data.get("sync_cursor")).strip()
                    if data.get("sync_cursor") is not None
                    else None
                ),
            )
            return web.json_response({"ok": True, "account": _serialise_record(patched)})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_delete_email_account(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        account_id = request.match_info["account_id"]
        try:
            actor = self._admin_actor(request)
            deleted = await self._tenant_admin_manager.delete_email_account(
                tenant_id=tenant_id,
                account_id=account_id,
                actor=actor,
            )
            return web.json_response({"ok": True, "existed": deleted})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_sync_email_account(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        account_id = request.match_info["account_id"]
        try:
            actor = self._admin_actor(request)
            data = await self._read_json_object(request)
            calendar_ops = data.get("calendar_operations")
            if calendar_ops is not None and not isinstance(calendar_ops, list):
                raise ValueError("calendar_operations must be an array")
            result = await self._tenant_admin_manager.sync_email_account(
                tenant_id=tenant_id,
                account_id=account_id,
                actor=actor,
                direction=str(data.get("direction") or "bi_directional"),
                idempotency_key=str(data.get("idempotency_key") or "").strip() or None,
                source=str(data.get("source") or "cgs-admin"),
                calendar_operations=calendar_ops,
                max_results=int(data.get("max_results") or 20),
            )
            return web.json_response({"ok": True, "sync": result})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)
        except Exception:
            log.exception("tenant_email_sync_failed", tenant_id=tenant_id, account_id=account_id)
            return web.json_response({"error": "Email sync failed"}, status=502)

    async def handle_tenant_list_email_critical(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            limit = self._parse_int(request.query.get("limit", "200"), "limit")
            rows = await self._tenant_admin_manager.list_email_critical_items(
                tenant_id=tenant_id,
                status=request.query.get("status"),
                severity=request.query.get("severity"),
                limit=limit,
            )
            return web.json_response({"critical_items": [_serialise_record(row) for row in rows]})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_list_email_insights(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            limit = self._parse_int(request.query.get("limit", "200"), "limit")
            min_confidence = request.query.get("min_confidence")
            min_confidence_value: float | None = None
            if isinstance(min_confidence, str) and min_confidence.strip():
                min_confidence_value = float(min_confidence)
            rows = await self._tenant_admin_manager.list_email_insights(
                tenant_id=tenant_id,
                insight_type=request.query.get("insight_type"),
                min_confidence=min_confidence_value,
                limit=limit,
            )
            return web.json_response({"insights": [_serialise_record(row) for row in rows]})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_reindex_email_insights(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        try:
            actor = self._admin_actor(request)
            data = await self._read_json_object(request)
            result = await self._tenant_admin_manager.reindex_email_insights(
                tenant_id=tenant_id,
                actor=actor,
                insight_type=(
                    str(data.get("insight_type")).strip()
                    if data.get("insight_type") is not None
                    else None
                ),
            )
            return web.json_response({"ok": True, "reindex": result})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_tenant_list_email_calendars(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        account_id = request.query.get("account_id")
        if not account_id:
            return web.json_response({"error": "Missing account_id query parameter"}, status=400)
        try:
            calendars = await self._tenant_admin_manager.list_google_calendars(
                tenant_id=tenant_id,
                account_id=account_id,
            )
            return web.json_response({"calendars": calendars})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)
        except Exception:
            log.exception("tenant_email_list_calendars_failed", tenant_id=tenant_id)
            return web.json_response({"error": "Failed to list calendars"}, status=502)

    async def handle_tenant_set_email_primary_calendar(self, request: web.Request) -> web.Response:
        if self._tenant_admin_manager is None:
            return web.json_response({"error": "Tenant admin is not configured"}, status=501)
        tenant_id = request.match_info["tenant_id"]
        account_id = request.match_info["account_id"]
        try:
            actor = self._admin_actor(request)
            data = await self._read_json_object(request)
            calendar_id = str(data.get("calendar_id") or "").strip()
            if not calendar_id:
                raise ValueError("Missing calendar_id")
            row = await self._tenant_admin_manager.set_email_primary_calendar(
                tenant_id=tenant_id,
                account_id=account_id,
                calendar_id=calendar_id,
                actor=actor,
            )
            return web.json_response({"ok": True, "account": _serialise_record(row)})
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=400)

    async def handle_bridge_messaging_ingest(self, request: web.Request) -> web.Response:
        """POST bridge ingest endpoint with HMAC auth + nonce replay protection."""
        tenant_id = request.match_info["tenant_id"]
        decision = self._trust_policy_evaluator.evaluate(
            tenant_id=tenant_id,
            action="messaging.ingest",
            context={"method": "POST", "subpath": "/messaging/ingest"},
        )
        if not decision.allowed:
            return web.json_response(
                {
                    "error": decision.message,
                    "code": decision.code,
                    "details": decision.details,
                },
                status=decision.status,
            )

        try:
            raw_body = await request.text()
        except Exception:
            raw_body = ""
        try:
            payload = _extract_json_object(raw_body)
        except Exception:
            return web.json_response({"error": "Invalid JSON body"}, status=400)

        try:
            self._verify_bridge_signature(
                request=request,
                tenant_id=tenant_id,
                raw_body=raw_body,
            )
        except RuntimeError as exc:
            return web.json_response({"error": str(exc)}, status=409)
        except ValueError as exc:
            return web.json_response({"error": str(exc)}, status=401)

        event_type = str(payload.get("event_type") or "").strip()
        chat_id = str(payload.get("chat_id") or "").strip()
        if not event_type:
            return web.json_response({"error": "Missing event_type"}, status=400)

        return web.json_response(
            {
                "ok": True,
                "accepted": True,
                "tenant_id": tenant_id,
                "event_type": event_type,
                "chat_id": chat_id,
                "received_at": datetime.now(UTC).isoformat(),
            },
            status=202,
        )

    # ------------------------------------------------------------------
    # Application factory
    # ------------------------------------------------------------------

    def create_app(self) -> web.Application:
        """Create the aiohttp application.

        Returns:
            The configured application.
        """
        app = web.Application(middlewares=[self.auth_middleware])

        # Core routes
        app.router.add_get("/health", self.handle_health)
        app.router.add_post("/handle", self.handle_request)
        app.router.add_post("/heartbeat", self.handle_heartbeat)
        app.router.add_get("/skills", self.handle_list_skills)
        app.router.add_get("/skills/{name}", self.handle_get_skill)
        app.router.add_get("/status", self.handle_status)
        app.router.add_get("/prompt-fragments", self.handle_prompt_fragments)
        app.router.add_get("/intents", self.handle_intents)
        app.router.add_get("/oauth/{provider}/authorize", self.handle_oauth_authorize)
        app.router.add_get("/oauth/{provider}/callback", self.handle_oauth_callback)
        app.router.add_get("/gmail/callback", self.handle_gmail_callback_alias)
        app.router.add_post(
            "/bridge/v1/tenants/{tenant_id}/messaging/ingest",
            self.handle_bridge_messaging_ingest,
        )

        # User management routes
        app.router.add_get("/users", self.handle_list_users)
        app.router.add_post("/users", self.handle_add_user)
        app.router.add_delete("/users/{user_id}", self.handle_delete_user)
        app.router.add_patch("/users/{user_id}/role", self.handle_patch_user_role)
        app.router.add_get("/users/audit", self.handle_audit_log)

        # Settings routes
        app.router.add_get("/settings", self.handle_list_settings)
        app.router.add_get("/settings/{namespace}/{key}", self.handle_get_setting)
        app.router.add_put("/settings/{namespace}/{key}", self.handle_put_setting)
        app.router.add_delete("/settings/{namespace}/{key}", self.handle_delete_setting)
        app.router.add_get("/secrets", self.handle_list_secrets)
        app.router.add_put("/secrets/{name}", self.handle_put_secret)
        app.router.add_delete("/secrets/{name}", self.handle_delete_secret)

        # Tenant-admin routes (internal-only; actor envelope required).
        tenant_prefix = "/admin/tenants/{tenant_id}"
        app.router.add_get(
            tenant_prefix + "/discord-users",
            self.handle_tenant_list_discord_users,
        )
        app.router.add_post(
            tenant_prefix + "/discord-users",
            self.handle_tenant_add_discord_user,
        )
        app.router.add_delete(
            tenant_prefix + "/discord-users/{discord_user_id}",
            self.handle_tenant_delete_discord_user,
        )
        app.router.add_patch(
            tenant_prefix + "/discord-users/{discord_user_id}/role",
            self.handle_tenant_patch_discord_user_role,
        )
        app.router.add_get(
            tenant_prefix + "/discord-bindings",
            self.handle_tenant_list_discord_bindings,
        )
        app.router.add_put(
            tenant_prefix + "/discord-bindings/guilds/{guild_id}",
            self.handle_tenant_put_guild_binding,
        )
        app.router.add_put(
            tenant_prefix + "/discord-bindings/channels/{channel_id}",
            self.handle_tenant_put_channel_binding,
        )
        app.router.add_delete(
            tenant_prefix + "/discord-bindings/channels/{channel_id}",
            self.handle_tenant_delete_channel_binding,
        )
        app.router.add_get(tenant_prefix + "/settings", self.handle_tenant_list_settings)
        app.router.add_put(
            tenant_prefix + "/settings/{namespace}/{key}",
            self.handle_tenant_put_setting,
        )
        app.router.add_delete(
            tenant_prefix + "/settings/{namespace}/{key}",
            self.handle_tenant_delete_setting,
        )
        app.router.add_get(tenant_prefix + "/secrets", self.handle_tenant_list_secrets)
        app.router.add_put(
            tenant_prefix + "/secrets/{name}",
            self.handle_tenant_put_secret,
        )
        app.router.add_delete(
            tenant_prefix + "/secrets/{name}",
            self.handle_tenant_delete_secret,
        )
        app.router.add_get(tenant_prefix + "/audit", self.handle_tenant_list_audit)
        app.router.add_get(
            tenant_prefix + "/email/providers/{provider}/oauth-app",
            self.handle_tenant_get_email_provider_config,
        )
        app.router.add_put(
            tenant_prefix + "/email/providers/{provider}/oauth-app",
            self.handle_tenant_put_email_provider_config,
        )
        app.router.add_post(
            tenant_prefix + "/email/oauth/{provider}/start",
            self.handle_tenant_start_email_oauth,
        )
        app.router.add_post(
            tenant_prefix + "/email/oauth/{provider}/exchange",
            self.handle_tenant_exchange_email_oauth,
        )
        app.router.add_get(
            tenant_prefix + "/email/accounts",
            self.handle_tenant_list_email_accounts,
        )
        app.router.add_patch(
            tenant_prefix + "/email/accounts/{account_id}",
            self.handle_tenant_patch_email_account,
        )
        app.router.add_delete(
            tenant_prefix + "/email/accounts/{account_id}",
            self.handle_tenant_delete_email_account,
        )
        app.router.add_post(
            tenant_prefix + "/email/accounts/{account_id}/sync",
            self.handle_tenant_sync_email_account,
        )
        app.router.add_get(
            tenant_prefix + "/email/critical",
            self.handle_tenant_list_email_critical,
        )
        app.router.add_get(
            tenant_prefix + "/email/insights",
            self.handle_tenant_list_email_insights,
        )
        app.router.add_post(
            tenant_prefix + "/email/insights/reindex",
            self.handle_tenant_reindex_email_insights,
        )
        app.router.add_get(
            tenant_prefix + "/email/calendars",
            self.handle_tenant_list_email_calendars,
        )
        app.router.add_put(
            tenant_prefix + "/email/accounts/{account_id}/calendar-primary",
            self.handle_tenant_set_email_primary_calendar,
        )

        self._app = app
        return app

    async def start(self) -> None:
        """Start the server."""
        if self._app is None:
            self.create_app()

        if self._app is None:  # pragma: no cover - create_app() sets self._app
            raise RuntimeError("create_app() must be called first")
        self._runner = web.AppRunner(self._app)
        await self._runner.setup()

        site = web.TCPSite(self._runner, self._host, self._port)
        await site.start()

        log.info("skills_server_started", host=self._host, port=self._port)

    async def stop(self) -> None:
        """Stop the server."""
        if self._runner:
            await self._runner.cleanup()
            self._runner = None
            log.info("skills_server_stopped")


async def run_server(  # pragma: no cover — starts infinite loop
    registry: SkillRegistry,
    api_secret: str | None = None,
    admin_actor_secret: str | None = None,
    host: str = "0.0.0.0",  # nosec B104 - Intentional for Docker container
    port: int = 8080,
    settings_manager: Any | None = None,
    secrets_manager: Any | None = None,
    tenant_admin_manager: TenantAdminManager | None = None,
    oauth_handlers: dict[str, OAuthCallbackHandler] | None = None,
    oauth_authorizers: dict[str, OAuthAuthorizeHandler] | None = None,
) -> None:
    """Run the skills server.

    This is the main entry point for the skills service container.

    Args:
        registry: The skill registry.
        api_secret: Optional API secret.
        host: Host to bind to.
        port: Port to listen on.
    """
    server = SkillsServer(
        registry=registry,
        api_secret=api_secret,
        admin_actor_secret=admin_actor_secret,
        host=host,
        port=port,
        settings_manager=settings_manager,
        secrets_manager=secrets_manager,
        tenant_admin_manager=tenant_admin_manager,
        oauth_handlers=oauth_handlers,
        oauth_authorizers=oauth_authorizers,
    )

    await server.start()

    # Wait indefinitely
    try:
        while True:
            await asyncio.sleep(3600)
    except asyncio.CancelledError:
        pass
    finally:
        await server.stop()


def main() -> None:  # pragma: no cover — CLI entry-point
    """Main entry point for the skills service."""
    from zetherion_ai.config import (
        get_settings,
        set_secret_resolver,
        set_settings_manager,
        set_tenant_admin_manager,
    )

    # Get configuration from environment
    api_secret = os.environ.get("SKILLS_API_SECRET")
    host = os.environ.get("SKILLS_HOST", "0.0.0.0")  # nosec B104 - Docker container
    port = int(os.environ.get("SKILLS_PORT", "8080"))

    # Create registry and register built-in skills
    registry = SkillRegistry()

    from zetherion_ai.skills.calendar import CalendarSkill
    from zetherion_ai.skills.dev_watcher import DevWatcherSkill
    from zetherion_ai.skills.email import EmailSkill
    from zetherion_ai.skills.gmail.skill import GmailSkill
    from zetherion_ai.skills.health_analyzer import HealthAnalyzerSkill
    from zetherion_ai.skills.milestone import MilestoneSkill
    from zetherion_ai.skills.profile_skill import ProfileSkill
    from zetherion_ai.skills.task_manager import TaskManagerSkill
    from zetherion_ai.skills.update_checker import UpdateCheckerSkill

    settings = get_settings()
    heartbeat_interval_seconds = 300
    check_interval_minutes = max(1, int(settings.auto_update_check_interval_minutes))
    check_every_n_beats = max(
        1,
        math.ceil((check_interval_minutes * 60) / heartbeat_interval_seconds),
    )
    github_token = (
        settings.github_token.get_secret_value() if settings.github_token is not None else None
    )
    updater_secret = settings.updater_secret or _resolve_updater_secret()
    gmail_skill = GmailSkill()
    email_skill = EmailSkill(default_provider="google", legacy_gmail_skill=gmail_skill)
    profile_skill = ProfileSkill()
    registry.register(TaskManagerSkill())
    registry.register(CalendarSkill())
    registry.register(profile_skill)
    registry.register(HealthAnalyzerSkill())
    registry.register(DevWatcherSkill())
    registry.register(MilestoneSkill())
    registry.register(gmail_skill)
    # Register email skill after Gmail so shared provider-agnostic intents win.
    registry.register(email_skill)
    registry.register(
        UpdateCheckerSkill(
            github_repo=settings.auto_update_repo,
            auto_apply=not settings.update_require_approval,
            enabled=settings.auto_update_enabled,
            github_token=github_token,
            updater_url=settings.updater_service_url,
            updater_secret=updater_secret,
            check_every_n_beats=check_every_n_beats,
            verify_signatures=settings.updater_verify_signatures,
            verify_identity=settings.updater_verify_identity,
            verify_oidc_issuer=settings.updater_verify_oidc_issuer,
            verify_rekor_url=settings.updater_verify_rekor_url,
            release_manifest_asset=settings.updater_release_manifest_asset,
            release_signature_asset=settings.updater_release_signature_asset,
            release_certificate_asset=settings.updater_release_certificate_asset,
        )
    )

    # Conditional: YouTube Skills (require Postgres + InferenceBroker)
    _yt_storage = None
    if settings.postgres_dsn:
        try:
            from zetherion_ai.agent.inference import InferenceBroker
            from zetherion_ai.skills.youtube.intelligence import YouTubeIntelligenceSkill
            from zetherion_ai.skills.youtube.management import YouTubeManagementSkill
            from zetherion_ai.skills.youtube.storage import YouTubeStorage
            from zetherion_ai.skills.youtube.strategy import YouTubeStrategySkill

            _yt_broker = InferenceBroker()
            _yt_storage = YouTubeStorage(dsn=settings.postgres_dsn)
            # Pool is created async in init_and_run; skills call storage after initialize_all
            registry.register(YouTubeIntelligenceSkill(storage=_yt_storage, broker=_yt_broker))
            registry.register(YouTubeManagementSkill(storage=_yt_storage, broker=_yt_broker))
            registry.register(YouTubeStrategySkill(storage=_yt_storage, broker=_yt_broker))
            log.info("youtube_skills_registered")
        except Exception as e:
            log.warning("youtube_skills_registration_failed", error=str(e))

    # Conditional: Client Provisioning (requires Postgres for TenantManager)
    _tenant_manager = None
    _tenant_inference_broker = None
    _personal_pool_factory = None
    _personal_storage_cls = None
    _personal_skill_cls = None
    if settings.postgres_dsn:
        from zetherion_ai.agent.inference import InferenceBroker
        from zetherion_ai.api.tenant import TenantManager
        from zetherion_ai.skills.client_app_watcher import ClientAppWatcherSkill
        from zetherion_ai.skills.client_insights import ClientInsightsSkill
        from zetherion_ai.skills.client_provisioning import ClientProvisioningSkill
        from zetherion_ai.skills.tenant_intelligence import TenantIntelligenceSkill

        _tenant_manager = TenantManager(dsn=settings.postgres_dsn)
        _tenant_inference_broker = InferenceBroker()
        registry.register(ClientProvisioningSkill(tenant_manager=_tenant_manager))
        registry.register(
            TenantIntelligenceSkill(
                inference_broker=_tenant_inference_broker,
                tenant_manager=_tenant_manager,
            )
        )
        registry.register(
            ClientInsightsSkill(
                inference_broker=_tenant_inference_broker,
                tenant_manager=_tenant_manager,
            )
        )
        registry.register(ClientAppWatcherSkill(tenant_manager=_tenant_manager))
        # Personal model requires direct PostgreSQL access.
        try:
            import asyncpg  # type: ignore[import-not-found,import-untyped]

            from zetherion_ai.personal.storage import PersonalStorage
            from zetherion_ai.skills.personal_model import PersonalModelSkill

            _personal_pool_factory = asyncpg.create_pool
            _personal_storage_cls = PersonalStorage
            _personal_skill_cls = PersonalModelSkill
        except Exception as e:
            log.warning("personal_model_bootstrap_failed", error=str(e))

    # Conditional: Fleet Insights (central instance only)
    if settings.telemetry_central_mode:
        from zetherion_ai.skills.fleet_insights import FleetInsightsSkill

        registry.register(FleetInsightsSkill())

    # Initialize all skills
    async def init_and_run() -> None:
        runtime_db_pool = None
        runtime_settings_manager = None
        runtime_secrets_manager = None
        tenant_admin_manager = None
        encryptor = None
        tenant_vector_memory = None
        personal_db_pool = None
        integration_pool = None
        oauth_handlers: dict[str, OAuthCallbackHandler] = {}
        oauth_authorizers: dict[str, OAuthAuthorizeHandler] = {}
        security_pipeline = None
        email_router = None
        email_inference_broker = None
        pool_min = max(1, int(settings.postgres_pool_min_size))
        pool_max = max(pool_min, int(settings.postgres_pool_max_size))
        pool_kwargs = {"min_size": pool_min, "max_size": pool_max}
        if _yt_storage is not None:
            await _yt_storage.initialize()
        if _tenant_manager is not None:
            await _tenant_manager.initialize()
        if settings.postgres_dsn:
            import asyncpg  # type: ignore[import-not-found,import-untyped]

            from zetherion_ai.admin import TenantAdminManager
            from zetherion_ai.discord.user_manager import _SCHEMA_SQL
            from zetherion_ai.security.encryption import FieldEncryptor
            from zetherion_ai.security.keys import KeyManager
            from zetherion_ai.security.secret_resolver import SecretResolver
            from zetherion_ai.security.secrets import SecretsManager
            from zetherion_ai.settings_manager import SettingsManager

            runtime_db_pool = await asyncpg.create_pool(
                dsn=settings.postgres_dsn,
                **pool_kwargs,
            )
            try:
                async with runtime_db_pool.acquire() as conn:
                    await conn.execute(_SCHEMA_SQL)
            except asyncpg.UniqueViolationError:
                log.info("skills_runtime_schema_ensured", note="concurrent creation resolved")
            else:
                log.info("skills_runtime_schema_ensured")
            runtime_settings_manager = SettingsManager()
            await runtime_settings_manager.initialize(runtime_db_pool)
            set_settings_manager(runtime_settings_manager)

            key_manager = KeyManager(
                passphrase=settings.encryption_passphrase.get_secret_value(),
                salt_path=settings.encryption_salt_path,
            )
            encryptor = FieldEncryptor(key=key_manager.key, strict=settings.encryption_strict)

            runtime_secrets_manager = SecretsManager(encryptor=encryptor)
            await runtime_secrets_manager.initialize(runtime_db_pool)
            set_secret_resolver(SecretResolver(runtime_secrets_manager, settings))

            try:
                from zetherion_ai.memory.qdrant import QdrantMemory

                tenant_vector_memory = QdrantMemory(encryptor=encryptor)
                await tenant_vector_memory.initialize()
            except Exception as exc:
                tenant_vector_memory = None
                log.warning("tenant_email_vector_memory_unavailable", error=str(exc))

            if tenant_vector_memory is not None:
                try:
                    from zetherion_ai.profile.builder import ProfileBuilder

                    profile_builder = ProfileBuilder(
                        memory=tenant_vector_memory,
                        inference_broker=None,
                        tier1_only=True,
                        auto_apply_threshold=float(settings.profile_confidence_threshold),
                        confirmation_expiry_hours=int(settings.profile_confirmation_expiry_hours),
                        max_pending_confirmations=int(settings.profile_max_pending_confirmations),
                    )
                    profile_skill.configure_dependencies(
                        memory=tenant_vector_memory,
                        profile_builder=profile_builder,
                    )
                    log.info("profile_skill_dependencies_wired", has_memory=True, has_builder=True)
                except Exception as exc:
                    profile_skill.configure_dependencies(memory=tenant_vector_memory)
                    log.warning(
                        "profile_skill_builder_wiring_failed",
                        error=str(exc),
                    )
            else:
                log.warning("profile_skill_memory_unavailable")

            tenant_admin_manager = TenantAdminManager(
                pool=runtime_db_pool,
                encryptor=encryptor,
                vector_memory=tenant_vector_memory,
            )
            await tenant_admin_manager.initialize()
            set_tenant_admin_manager(tenant_admin_manager)
        if settings.work_router_enabled and settings.postgres_dsn:
            import asyncpg  # type: ignore[import-not-found,import-untyped]

            from zetherion_ai.agent.inference import InferenceBroker
            from zetherion_ai.integrations.providers.google import GoogleProviderAdapter
            from zetherion_ai.integrations.providers.outlook import OutlookProviderAdapter
            from zetherion_ai.integrations.storage import IntegrationStorage
            from zetherion_ai.routing.email_router import EmailRouter
            from zetherion_ai.routing.registry import (
                ProviderAdapters,
                ProviderCapabilities,
                ProviderRegistry,
            )
            from zetherion_ai.routing.task_calendar_router import TaskCalendarRouter
            from zetherion_ai.security.content_pipeline import ContentSecurityPipeline
            from zetherion_ai.skills.gmail.accounts import GmailAccountManager

            integration_pool = await asyncpg.create_pool(
                dsn=settings.postgres_dsn,
                **pool_kwargs,
            )
            if encryptor is None:
                raise RuntimeError("Encryption is not initialized")

            account_manager = GmailAccountManager(integration_pool, encryptor)
            await account_manager.ensure_schema()

            integration_storage = IntegrationStorage(integration_pool)
            await integration_storage.ensure_schema()

            def google_auth_resolver() -> Any:
                return _resolve_google_oauth(settings=settings)

            def try_google_auth() -> Any | None:
                try:
                    return google_auth_resolver()
                except ValueError:
                    return None

            google_adapter = GoogleProviderAdapter(
                account_manager,
                auth=try_google_auth(),
                auth_resolver=try_google_auth,
            )
            provider_registry = ProviderRegistry()
            provider_registry.register(
                "google",
                adapters=ProviderAdapters(
                    email=google_adapter,
                    task=google_adapter,
                    calendar=google_adapter,
                ),
                capabilities=ProviderCapabilities(
                    email_read=True,
                    task_read=True,
                    task_write=True,
                    calendar_read=True,
                    calendar_write=True,
                    two_way_sync=True,
                    cross_calendar_conflicts=True,
                ),
            )

            if settings.provider_outlook_enabled:
                outlook_adapter = OutlookProviderAdapter(enabled=True)
                provider_registry.register(
                    "outlook",
                    adapters=ProviderAdapters(
                        email=outlook_adapter,
                        task=outlook_adapter,
                        calendar=outlook_adapter,
                    ),
                    capabilities=ProviderCapabilities(),
                )

            security_pipeline = ContentSecurityPipeline()
            task_calendar_router = TaskCalendarRouter(
                storage=integration_storage,
                providers=provider_registry,
                security=security_pipeline,
            )

            async def resolve_email_user_context(user_id: int) -> dict[str, Any]:
                timezone_name = "UTC"
                try:
                    async with integration_pool.acquire() as conn:
                        row = await conn.fetchrow(
                            "SELECT timezone FROM personal_profile WHERE user_id = $1 LIMIT 1",
                            user_id,
                        )
                    if row is not None:
                        candidate = row["timezone"]
                        if isinstance(candidate, str) and candidate.strip():
                            timezone_name = candidate.strip()
                except Exception as exc:
                    log.debug(
                        "email_user_context_lookup_failed",
                        user_id=user_id,
                        error=str(exc),
                    )
                return {"timezone": timezone_name}

            email_inference_broker = InferenceBroker()

            email_router = EmailRouter(
                storage=integration_storage,
                providers=provider_registry,
                security=security_pipeline,
                task_calendar_router=task_calendar_router,
                inference=email_inference_broker,
                email_security_gate_enabled=settings.email_security_gate_enabled,
                local_extraction_required=settings.local_extraction_required,
                user_context_resolver=resolve_email_user_context,
                attachment_handling_enabled=False,
            )
            email_skill.configure(
                router=email_router,
                storage=integration_storage,
                providers=provider_registry,
                default_provider="google",
                account_manager=account_manager,
            )

            oauth_handlers["google"] = _build_google_oauth_handler(
                auth_resolver=google_auth_resolver,
                account_manager=account_manager,
                integration_storage=integration_storage,
            )
            oauth_authorizers["google"] = _build_google_oauth_authorize_handler(
                auth_resolver=google_auth_resolver,
            )

            async def email_oauth_authorizer(*, user_id: int, provider: str) -> dict[str, str]:
                if provider != "google":
                    raise ValueError(f"Provider '{provider}' is not configured for OAuth linking")
                auth = google_auth_resolver()
                auth_url, state = auth.generate_auth_url(user_id)
                return {"provider": provider, "auth_url": auth_url, "state": state}

            email_skill.configure(oauth_authorizer=email_oauth_authorizer)

            if tenant_admin_manager is not None:
                from zetherion_ai.agent.providers import TaskType

                async def tenant_email_critical_scorer(
                    subject: str,
                    body_preview: str,
                ) -> dict[str, Any] | None:
                    prompt = (
                        "You are scoring whether an inbound business email is critical.\n"
                        "Return strict JSON only with keys score (0-1 float) and reason_codes"
                        " (array of short snake_case strings).\n"
                        "Subject:\n"
                        f"{subject}\n\n"
                        "Body preview:\n"
                        f"{body_preview[:1200]}"
                    )
                    infer_result = email_inference_broker.infer(
                        prompt,
                        TaskType.CLASSIFICATION,
                        max_tokens=180,
                        temperature=0.1,
                    )
                    result = (
                        await infer_result if asyncio.iscoroutine(infer_result) else infer_result
                    )
                    payload = _extract_json_object(result.content)
                    if not payload:
                        return None
                    score_raw = payload.get("score")
                    reasons_raw = payload.get("reason_codes")
                    if isinstance(score_raw, int | float):
                        score = float(score_raw)
                    elif isinstance(score_raw, str):
                        try:
                            score = float(score_raw)
                        except ValueError:
                            return None
                    else:
                        return None
                    if not isinstance(reasons_raw, list):
                        reasons_raw = []
                    reason_codes = [str(code).strip() for code in reasons_raw if str(code).strip()]
                    return {"score": score, "reason_codes": reason_codes}

                tenant_admin_manager.set_critical_scorer(tenant_email_critical_scorer)
        if (
            _personal_pool_factory is not None
            and _personal_storage_cls is not None
            and _personal_skill_cls is not None
        ):
            personal_db_pool = await _personal_pool_factory(
                dsn=settings.postgres_dsn,
                **pool_kwargs,
            )
            personal_storage = _personal_storage_cls(personal_db_pool)
            await personal_storage.ensure_schema()
            registry.register(_personal_skill_cls(storage=personal_storage))
            if email_router is not None:
                email_router.set_personal_storage(personal_storage)
            log.info("personal_model_skill_registered")
        await registry.initialize_all()
        try:
            await run_server(
                registry=registry,
                api_secret=api_secret,
                admin_actor_secret=api_secret,
                host=host,
                port=port,
                settings_manager=runtime_settings_manager,
                secrets_manager=runtime_secrets_manager,
                tenant_admin_manager=tenant_admin_manager,
                oauth_handlers=oauth_handlers,
                oauth_authorizers=oauth_authorizers,
            )
        finally:
            if security_pipeline is not None:
                await security_pipeline.close()
            if integration_pool is not None:
                await integration_pool.close()
            if runtime_db_pool is not None:
                await runtime_db_pool.close()
            if personal_db_pool is not None:
                await personal_db_pool.close()
            if tenant_vector_memory is not None:
                await tenant_vector_memory.close()
            if _tenant_inference_broker is not None:
                await _tenant_inference_broker.close()
            if email_inference_broker is not None:
                await email_inference_broker.close()

    try:
        asyncio.run(init_and_run())
    except KeyboardInterrupt:
        log.info("skills_server_shutdown")


if __name__ == "__main__":
    main()
